worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream dhis2 {
    server dhis2:8080 max_fails=3 fail_timeout=60s;
  }

  gzip on;
  gzip_types
    "application/json;charset=utf-8" application/json
    "application/javascript;charset=utf-8" application/javascript text/javascript
    "application/xml;charset=utf-8" application/xml text/xml
    "text/css;charset=utf-8" text/css
    "text/plain;charset=utf-8" text/plain;

  server {
    listen 80;
    
    client_max_body_size 10m;

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://dhis2;
    }
  }
}